In [72]:
import numpy as np
import torch

In [73]:
# Inputs (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float64')

In [74]:
# Target (apples)
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float64')

In [75]:
# Convert inputs and targets to tensors

x_inputs = torch.from_numpy(inputs)
x_targets = torch.from_numpy(targets)

x_inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]], dtype=torch.float64)

In [76]:
x_weights = torch.randn(x_inputs.shape[1],x_targets.shape[1],dtype=torch.float64, requires_grad=True )
x_biases = torch.randn(x_inputs.shape[0],x_targets.shape[1], dtype=torch.float64, requires_grad=True)
x_weights

tensor([[ 0.9978],
        [ 0.9483],
        [-0.5222]], dtype=torch.float64, requires_grad=True)

In [77]:
model = torch.matmul(x_inputs,x_weights)
model = torch.add(model,x_biases)
model

tensor([[113.0395],
        [141.7140],
        [183.6377],
        [123.1684],
        [123.3100]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [78]:
x_targets

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]], dtype=torch.float64)

In [79]:
diff = torch.subtract(model,x_targets)
torch.square_(diff)

loss  = torch.sum(diff)/len(diff)
loss

tensor(4353.0527, dtype=torch.float64, grad_fn=<DivBackward0>)

In [81]:
loss.backward(retain_graph=True)

In [82]:
x_weights.grad


tensor([[21626.3217],
        [19300.7425],
        [12201.8487]], dtype=torch.float64)

In [83]:
x_biases.grad

tensor([[45.6316],
        [48.5712],
        [51.7101],
        [80.9347],
        [16.2480]], dtype=torch.float64)